// Expanded Question Database - 100 Questions per Category
const expandedQuestions = {
  Sports: [
    {q: "Who won the ICC Cricket World Cup 2011?", o: ["India", "Australia", "Sri Lanka", "England"], a: 0},
    {q: "Which country won FIFA WC 2018?", o: ["Brazil", "France", "Germany", "Argentina"], a: 1},
    {q: "Who is known as 'The God of Cricket'?", o: ["Sachin Tendulkar", "Virat Kohli", "MS Dhoni", "Ricky Ponting"], a: 0},
    {q: "Which tennis player has most Grand Slam titles?", o: ["Federer", "Nadal", "Djokovic", "Sampras"], a: 1},
    {q: "In which sport is 'The Ryder Cup' played?", o: ["Golf", "Tennis", "Football", "Basketball"], a: 0},
    {q: "Who is the highest run scorer in IPL history?", o: ["Virat Kohli", "Rohit Sharma", "David Warner", "Chris Gayle"], a: 0},
    {q: "Which country has won most FIFA World Cups?", o: ["Germany", "Argentina", "Brazil", "Italy"], a: 2},
    {q: "Which NBA player has most championship rings?", o: ["Michael Jordan", "LeBron James", "Bill Russell", "Kobe Bryant"], a: 2},
    {q: "In which year did Usain Bolt set his 100m world record?", o: ["2008", "2009", "2010", "2011"], a: 1},
    {q: "Who is the captain of Indian Cricket Team (2023)?", o: ["Rohit Sharma", "Virat Kohli", "KL Rahul", "Hardik Pandya"], a: 0},
    {q: "Which country invented cricket?", o: ["England", "Australia", "India", "West Indies"], a: 0},
    {q: "What is the national sport of Canada?", o: ["Ice Hockey", "Lacrosse", "Basketball", "Baseball"], a: 0},
    {q: "Who won the Ballon d'Or 2022?", o: ["Messi", "Ronaldo", "Benzema", "Mbappe"], a: 2},
    {q: "Which country has won most Olympic gold medals?", o: ["USA", "China", "Russia", "UK"], a: 0},
    {q: "What is the length of a cricket pitch?", o: ["20 yards", "22 yards", "24 yards", "26 yards"], a: 1},
    {q: "Who is known as 'The King' in NBA?", o: ["LeBron James", "Michael Jordan", "Kobe Bryant", "Stephen Curry"], a: 0},
    {q: "Which country won the first Cricket World Cup in 1975?", o: ["West Indies", "Australia", "England", "India"], a: 0},
    {q: "Who holds the record for most goals in FIFA World Cup?", o: ["Miroslav Klose", "Ronaldo", "Pele", "Gerd Muller"], a: 0},
    {q: "What is the height of a basketball hoop?", o: ["9 feet", "10 feet", "11 feet", "12 feet"], a: 1},
    {q: "Which tennis tournament is played on grass?", o: ["Wimbledon", "US Open", "French Open", "Australian Open"], a: 0},
    {q: "Who is the fastest bowler in cricket history?", o: ["Shoaib Akhtar", "Brett Lee", "Mitchell Starc", "Waqar Younis"], a: 0},
    {q: "Which country has won most Rugby World Cups?", o: ["New Zealand", "South Africa", "Australia", "England"], a: 0},
    {q: "What is the distance of a marathon?", o: ["42.195 km", "40 km", "45 km", "50 km"], a: 0},
    {q: "Who won the most Formula 1 championships?", o: ["Michael Schumacher", "Lewis Hamilton", "Sebastian Vettel", "Ayrton Senna"], a: 1},
    {q: "Which country invented volleyball?", o: ["USA", "Brazil", "China", "Russia"], a: 0},
    {q: "What is the weight of a boxing glove for professional fights?", o: ["8 oz", "10 oz", "12 oz", "14 oz"], a: 1},
    {q: "Who is known as 'The Flying Sikh'?", o: ["Milkha Singh", "PT Usha", "Anju Bobby George", "Abhinav Bindra"], a: 0},
    {q: "Which country has won most ICC T20 World Cups?", o: ["West Indies", "India", "Australia", "England"], a: 0},
    {q: "What is the duration of a professional boxing round?", o: ["3 minutes", "2 minutes", "4 minutes", "5 minutes"], a: 0},
    {q: "Who holds the record for most centuries in Test cricket?", o: ["Sachin Tendulkar", "Jacques Kallis", "Ricky Ponting", "Virat Kohli"], a: 0},
    {q: "Which country won the first FIFA World Cup?", o: ["Uruguay", "Brazil", "Argentina", "Italy"], a: 0},
    {q: "What is the maximum score in ten-pin bowling?", o: ["300", "250", "200", "350"], a: 0},
    {q: "Who is known as 'The Black Pearl' in football?", o: ["Pele", "Maradona", "Ronaldo", "Messi"], a: 0},
    {q: "Which sport uses terms like 'love', 'deuce', and 'advantage'?", o: ["Tennis", "Badminton", "Table Tennis", "Squash"], a: 0},
    {q: "Who won the most Wimbledon titles in men's singles?", o: ["Roger Federer", "Pete Sampras", "Novak Djokovic", "Rafael Nadal"], a: 0},
    {q: "What is the national sport of Japan?", o: ["Sumo Wrestling", "Karate", "Judo", "Baseball"], a: 0},
    {q: "Which country has won most hockey World Cups?", o: ["Pakistan", "India", "Netherlands", "Germany"], a: 0},
    {q: "Who is the highest wicket-taker in Test cricket?", o: ["Muttiah Muralitharan", "Shane Warne", "Anil Kumble", "James Anderson"], a: 0},
    {q: "What is the distance of a swimming pool for Olympic events?", o: ["50 meters", "25 meters", "100 meters", "75 meters"], a: 0},
    {q: "Who won the most Olympic gold medals in athletics?", o: ["Usain Bolt", "Carl Lewis", "Paavo Nurmi", "Ray Ewry"], a: 3},
    {q: "Which country invented badminton?", o: ["England", "India", "China", "Malaysia"], a: 0},
    {q: "What is the duration of a football match?", o: ["90 minutes", "80 minutes", "100 minutes", "85 minutes"], a: 0},
    {q: "Who is known as 'The Iron Man' in Indian cricket?", o: ["Rahul Dravid", "MS Dhoni", "Virender Sehwag", "Sachin Tendulkar"], a: 0},
    {q: "Which country has won most UEFA European Championships?", o: ["Germany", "Spain", "Italy", "France"], a: 0},
    {q: "What is the weight of a shot put for men?", o: ["7.26 kg", "6 kg", "8 kg", "5 kg"], a: 0},
    {q: "Who holds the record for most goals in a calendar year?", o: ["Lionel Messi", "Cristiano Ronaldo", "Gerd Muller", "Pele"], a: 0},
    {q: "Which sport is played on the largest field?", o: ["Polo", "Football", "Cricket", "Rugby"], a: 0},
    {q: "Who won the most Grand Slam titles in women's tennis?", o: ["Serena Williams", "Steffi Graf", "Martina Navratilova", "Margaret Court"], a: 3},
    {q: "What is the height of a volleyball net for men?", o: ["2.43 meters", "2.24 meters", "2.50 meters", "2.30 meters"], a: 0},
    {q: "Which country has won most World Athletics Championships?", o: ["USA", "Kenya", "Jamaica", "Russia"], a: 0},
    {q: "Who is known as 'The Destroyer' in cricket?", o: ["Virender Sehwag", "Chris Gayle", "AB de Villiers", "David Warner"], a: 0},
    {q: "What is the duration of a basketball quarter in NBA?", o: ["12 minutes", "10 minutes", "15 minutes", "8 minutes"], a: 0},
    {q: "Which country invented table tennis?", o: ["England", "China", "Japan", "Korea"], a: 0},
    {q: "Who won the most Tour de France titles?", o: ["Lance Armstrong", "Eddy Merckx", "Bernard Hinault", "Miguel Indurain"], a: 1},
    {q: "What is the weight of a golf ball?", o: ["45.93 grams", "40 grams", "50 grams", "35 grams"], a: 0},
    {q: "Who is known as 'The Captain Cool' in cricket?", o: ["MS Dhoni", "Virat Kohli", "Rohit Sharma", "KL Rahul"], a: 0},
    {q: "Which country has won most boxing Olympic gold medals?", o: ["USA", "Cuba", "Russia", "China"], a: 1},
    {q: "What is the distance of a cycling track in velodrome?", o: ["250 meters", "200 meters", "300 meters", "400 meters"], a: 0},
    {q: "Who holds the record for most sixes in international cricket?", o: ["Chris Gayle", "MS Dhoni", "AB de Villiers", "Shahid Afridi"], a: 0},
    {q: "Which sport uses terms like 'birdie', 'eagle', and 'albatross'?", o: ["Golf", "Tennis", "Badminton", "Table Tennis"], a: 0},
    {q: "Who won the most FIFA World Cup Golden Boots?", o: ["Miroslav Klose", "Ronaldo", "Gerd Muller", "Just Fontaine"], a: 0},
    {q: "What is the height of a football goalpost?", o: ["8 feet", "7 feet", "9 feet", "6 feet"], a: 0},
    {q: "Who is known as 'The Wall' in cricket?", o: ["Rahul Dravid", "Jacques Kallis", "Alastair Cook", "Kumar Sangakkara"], a: 0},
    {q: "Which country has won most World Cup titles in women's football?", o: ["USA", "Germany", "Norway", "Japan"], a: 0},
    {q: "What is the weight of a javelin for men?", o: ["800 grams", "700 grams", "900 grams", "600 grams"], a: 0},
    {q: "Who holds the record for most Test matches as captain?", o: ["Stephen Fleming", "MS Dhoni", "Graeme Smith", "Ricky Ponting"], a: 2},
    {q: "Which sport is played on ice with stones and brooms?", o: ["Curling", "Ice Hockey", "Bobsleigh", "Skeleton"], a: 0},
    {q: "Who won the most Formula 1 races?", o: ["Lewis Hamilton", "Michael Schumacher", "Sebastian Vettel", "Alain Prost"], a: 0},
    {q: "What is the circumference of a basketball?", o: ["29.5 inches", "28 inches", "30 inches", "27 inches"], a: 0},
    {q: "Who is known as 'The Universal Boss' in cricket?", o: ["Chris Gayle", "AB de Villiers", "MS Dhoni", "Virat Kohli"], a: 0},
    {q: "Which country has won most World Aquatics Championships?", o: ["USA", "China", "Russia", "Australia"], a: 0},
    {q: "What is the duration of a hockey match?", o: ["70 minutes", "60 minutes", "80 minutes", "90 minutes"], a: 0},
    {q: "Who holds the record for most goals in Champions League?", o: ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], a: 0},
    {q: "Which sport uses a shuttlecock?", o: ["Badminton", "Tennis", "Squash", "Racquetball"], a: 0},
    {q: "What is the height of a tennis net?", o: ["3 feet", "2.5 feet", "3.5 feet", "2 feet"], a: 0},
    {q: "Who won the most Grand Slam titles in men's doubles?", o: ["Mike Bryan", "Bob Bryan", "Daniel Nestor", "Leander Paes"], a: 0},
    {q: "Which country has won most World Cup titles in rugby sevens?", o: ["New Zealand", "Fiji", "South Africa", "Australia"], a: 0},
    {q: "What is the weight of a discus for men?", o: ["2 kg", "1.75 kg", "2.5 kg", "1.5 kg"], a: 0},
    {q: "Who is known as 'The Finisher' in cricket?", o: ["MS Dhoni", "AB de Villiers", "Michael Bevan", "Lance Klusener"], a: 0},
    {q: "Which sport involves riding waves?", o: ["Surfing", "Water Skiing", "Wakeboarding", "Kiteboarding"], a: 0},
    {q: "What is the distance of a marathon in miles?", o: ["26.2 miles", "25 miles", "27 miles", "24 miles"], a: 0},
    {q: "Who won the most ATP Masters 1000 titles?", o: ["Novak Djokovic", "Rafael Nadal", "Roger Federer", "Andy Murray"], a: 0},
    {q: "Which country has won most World Cup titles in handball?", o: ["France", "Germany", "Spain", "Sweden"], a: 0},
    {q: "What is the height of a badminton net?", o: ["1.55 meters", "1.50 meters", "1.60 meters", "1.45 meters"], a: 0},
    {q: "Who holds the record for most catches in Test cricket?", o: ["Rahul Dravid", "Jacques Kallis", "Mahela Jayawardene", "Alastair Cook"], a: 0},
    {q: "Which sport involves climbing artificial walls?", o: ["Sport Climbing", "Mountaineering", "Bouldering", "Rock Climbing"], a: 0},
    {q: "What is the duration of a boxing match for world title?", o: ["12 rounds", "10 rounds", "15 rounds", "8 rounds"], a: 0},
    {q: "Who won the most World Cup titles in skiing?", o: ["Marcel Hirscher", "Ingemar Stenmark", "Hermann Maier", "Alberto Tomba"], a: 1},
    {q: "Which country has won most World Cup titles in volleyball?", o: ["Brazil", "Italy", "Russia", "USA"], a: 0},
    {q: "What is the weight of a hammer for men?", o: ["7.26 kg", "6 kg", "8 kg", "5 kg"], a: 0},
    {q: "Who is known as 'The Hitman' in cricket?", o: ["Rohit Sharma", "Virat Kohli", "David Warner", "Babar Azam"], a: 0},
    {q: "Which sport involves riding horses and shooting?", o: ["Modern Pentathlon", "Equestrian", "Polo", "Show Jumping"], a: 0},
    {q: "What is the distance of a triathlon swimming leg?", o: ["1.5 km", "1 km", "2 km", "1.2 km"], a: 0},
    {q: "Who won the most World Cup titles in gymnastics?", o: ["Simone Biles", "Vitaly Scherbo", "Kohei Uchimura", "Aliya Mustafina"], a: 1},
    {q: "Which country has won most World Cup titles in wrestling?", o: ["Russia", "USA", "Iran", "Turkey"], a: 0},
    {q: "What is the height of a table tennis net?", o: ["15.25 cm", "12 cm", "18 cm", "10 cm"], a: 0},
    {q: "Who holds the record for most stumpings in ODI cricket?", o: ["MS Dhoni", "Kumar Sangakkara", "Romesh Kaluwitharana", "Jeff Dujon"], a: 0},
    {q: "Which sport involves sliding down ice tracks?", o: ["Skeleton", "Luge", "Bobsleigh", "Curling"], a: 0},
    {q: "What is the duration of a water polo match?", o: ["32 minutes", "30 minutes", "35 minutes", "28 minutes"], a: 0},
    {q: "Who won the most World Cup titles in archery?", o: ["South Korea", "USA", "China", "Italy"], a: 0},
    {q: "Which country has won most World Cup titles in sailing?", o: ["Great Britain", "USA", "Australia", "New Zealand"], a: 0},
    {q: "What is the weight of a bowling ball?", o: ["6-16 pounds", "5-15 pounds", "7-17 pounds", "4-14 pounds"], a: 0},
    {q: "Who is known as 'The King of Swing' in cricket?", o: ["James Anderson", "Dale Steyn", "Mitchell Starc", "Josh Hazlewood"], a: 0},
    {q: "Which sport involves performing acrobatics in water?", o: ["Synchronized Swimming", "Diving", "Water Ballet", "Aqua Aerobics"], a: 0},
    {q: "What is the distance of a cycling road race in Olympics?", o: ["234 km", "200 km", "250 km", "180 km"], a: 0},
    {q: "Who won the most World Cup titles in fencing?", o: ["Italy", "France", "Germany", "Russia"], a: 0},
    {q: "Which country has won most World Cup titles in canoeing?", o: ["Germany", "Hungary", "France", "Czech Republic"], a: 0},
    {q: "What is the height of a basketball hoop for women?", o: ["10 feet", "9 feet", "8.5 feet", "11 feet"], a: 0},
    {q: "Who holds the record for most runs in T20 internationals?", o: ["Virat Kohli", "Babar Azam", "Rohit Sharma", "Martin Guptill"], a: 0},
    {q: "Which sport involves fighting with swords?", o: ["Fencing", "Kendo", "Eskrima", "Sword Fighting"], a: 0},
    {q: "What is the duration of a rugby sevens match?", o: ["14 minutes", "20 minutes", "10 minutes", "15 minutes"], a: 0},
    {q: "Who won the most World Cup titles in rowing?", o: ["Great Britain", "Germany", "USA", "Australia"], a: 0},
    {q: "Which country has won most World Cup titles in shooting?", o: ["USA", "China", "Russia", "Germany"], a: 0},
    {q: "What is the weight of a discus for women?", o: ["1 kg", "800 grams", "1.2 kg", "900 grams"], a: 0},
    {q: "Who is known as 'The Chinaman' in cricket?", o: ["Ellis Achong", "Bishan Singh Bedi", "Shane Warne", "Muttiah Muralitharan"], a: 0},
    {q: "Which sport involves riding waves on a board?", o: ["Surfing", "Skateboarding", "Snowboarding", "Wakeboarding"], a: 0},
    {q: "What is the duration of a handball match?", o: ["60 minutes", "50 minutes", "70 minutes", "40 minutes"], a: 0}
  ],
  
  Entertainment: [
    {q: "Who directed the movie 'Inception'?", o: ["Steven Spielberg", "Christopher Nolan", "Martin Scorsese", "Quentin Tarantino"], a: 1},
    {q: "Which movie won the Oscar for Best Picture in 2020?", o: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], a: 2},
    {q: "In 'Money Heist', what is the name of the main character?", o: ["Lisbon", "Berlin", "Professor", "Rio"], a: 2},
    {q: "Which web series features the Upside Down?", o: ["Stranger Things", "Black Mirror", "Dark", "The OA"], a: 0},
    {q: "What is the name of Walter White's alter ego in Breaking Bad?", o: ["Heisenberg", "Jesse", "Gus", "Saul"], a: 0},
    {q: "In 'Squid Game', what is the final game?", o: ["Tug of War", "Glass Bridge", "Squid Game", "Red Light Green Light"], a: 2},
    {q: "Which actor plays the lead role in 'Alice in Borderland'?", o: ["Kento Yamazaki", "Tao Tsuchiya", "Nijiro Murakami", "Ayaka Miyoshi"], a: 0},
    {q: "In 'Stranger Things', what is Eleven's real name?", o: ["Jane", "Sarah", "Emily", "Max"], a: 0},
    {q: "Which web series is about a chess prodigy?", o: ["The Queen's Gambit", "The Crown", "Mindhunter", "Narcos"], a: 0},
    {q: "In 'Money Heist', which city is the Royal Mint located?", o: ["Madrid", "Barcelona", "Seville", "Valencia"], a: 0},
    {q: "Who plays the role of 'The Witcher' in the Netflix series?", o: ["Henry Cavill", "Jason Momoa", "Chris Hemsworth", "Tom Hardy"], a: 0},
    {q: "In 'Dark', what is the name of the German town?", o: ["Windan", "Windenburg", "Winden", "Winder"], a: 2},
    {q: "Which web series features a high school chemistry teacher turned drug dealer?", o: ["Breaking Bad", "Narcos", "Ozark", "Power"], a: 0},
    {q: "In 'The Crown', who plays Queen Elizabeth II?", o: ["Claire Foy", "Olivia Colman", "Imelda Staunton", "All of the above"], a: 3},
    {q: "Which web series is about a post-apocalyptic world with zombies?", o: ["The Walking Dead", "Stranger Things", "Dark", "Black Mirror"], a: 0},
    {q: "Who directed 'Avengers: Endgame'?", o: ["Russo Brothers", "Joss Whedon", "James Gunn", "Taika Waititi"], a: 0},
    {q: "What is real name of Iron Man?", o: ["Tony Stark", "Steve Rogers", "Bruce Banner", "Clint Barton"], a: 0},
    {q: "Which actor plays Thor in MCU?", o: ["Chris Hemsworth", "Chris Evans", "Chris Pratt", "Chris Pine"], a: 0},
    {q: "Who is villain in 'The Dark Knight'?", o: ["Joker", "Bane", "Riddler", "Penguin"], a: 0},
    {q: "Which Marvel movie introduced Black Panther?", o: ["Captain America: Civil War", "Avengers: Age of Ultron", "Guardians of Galaxy", "Thor: Ragnarok"], a: 0},
    {q: "What is real name of Captain America?", o: ["Steve Rogers", "Bucky Barnes", "Sam Wilson", "Tony Stark"], a: 0},
    {q: "Who plays Wolverine in X-Men movies?", o: ["Hugh Jackman", "Ryan Reynolds", "James McAvoy", "Michael Fassbender"], a: 0},
    {q: "Which actor plays Superman in 'Man of Steel'?", o: ["Henry Cavill", "Brandon Routh", "Christopher Reeve", "Tyler Hoechlin"], a: 0},
    {q: "Who plays Spider-Man in MCU?", o: ["Tom Holland", "Tobey Maguire", "Andrew Garfield", "Jake Gyllenhaal"], a: 0},
    {q: "Which Marvel movie features villain Thanos?", o: ["Avengers: Infinity War", "Guardians of Galaxy", "Doctor Strange", "Ant-Man"], a: 0},
{ q:"Who is the first Avenger?", o:["Iron Man","Captain America","Thor","Hulk"], a:1 },
{ q:"What metal is Wolverine's claws made of?", o:["Vibranium","Adamantium","Steel","Titanium"], a:1 },
{ q:"Who snapped fingers in Infinity War?", o:["Thor","Iron Man","Thanos","Hulk"], a:2 },
{ q:"Doctor Strange guards which stone?", o:["Time","Mind","Soul","Power"], a:0 },
{ q:"Real name of Black Panther?", o:["T’Challa","M’Baku","Killmonger","N’Jadaka"], a:0 },
{ q:"Who created Ultron?", o:["Bruce","Tony","Both","Vision"], a:2 },
{ q:"Spider-Man mentor in MCU?", o:["Nick Fury","Tony Stark","Happy","Strange"], a:1 },
{ q:"Thor’s hammer name?", o:["Stormbreaker","Mjolnir","Gungnir","Axe"], a:1 },
{ q:"Scarlet Witch power source?", o:["Reality Stone","Mind Stone","Dark Magic","Chaos"], a:3 },
{ q:"Leader of Guardians?", o:["Rocket","Groot","Star-Lord","Gamora"], a:2 },
{ q:"Who killed Thanos finally?", o:["Thor","Iron Man","Captain","Wanda"], a:1 },
{ q:"Ant-Man real name?", o:["Scott Lang","Hank Pym","Hope","Luis"], a:0 },
{ q:"Vision stone color?", o:["Blue","Yellow","Red","Green"], a:1 },
{ q:"Loki is Thor’s?", o:["Brother","Friend","Enemy","Cousin"], a:0 },
{ q:"Marvel multiverse broke in?", o:["Endgame","Loki","No Way Home","WandaVision"], a:2 },
{ q:"Nick Fury eye lost due to?", o:["War","Alien","Cat","Explosion"], a:2 },
{ q:"Who is Winter Soldier?", o:["Sam","Bucky","Steve","Clint"], a:1 },
{ q:"Captain shield metal?", o:["Steel","Adamantium","Vibranium","Iron"], a:2 },
{ q:"Who leads Avengers?", o:["Thor","Iron Man","Cap","Hulk"], a:2 },
{ q:"Thanos planet?", o:["Titan","Xandar","Asgard","Sakaar"], a:0 },

/* ---------- DC (20) ---------- */
{ q:"Batman city?", o:["Metropolis","Gotham","Central","Star"], a:1 },
{ q:"Superman weakness?", o:["Magic","Kryptonite","Fire","Ice"], a:1 },
{ q:"Wonder Woman weapon?", o:["Sword","Shield","Lasso","Bow"], a:2 },
{ q:"Flash fastest speed source?", o:["Wind","Speed Force","Time","Energy"], a:1 },
{ q:"Joker enemy of?", o:["Superman","Flash","Batman","Aquaman"], a:2 },
{ q:"Aquaman kingdom?", o:["Atlantis","Olympus","Asgard","Wakanda"], a:0 },
{ q:"Batman real name?", o:["Bruce Wayne","Clark Kent","Barry Allen","Hal Jordan"], a:0 },
{ q:"Green Lantern power?", o:["Ring","Sword","Hammer","Stone"], a:0 },
{ q:"Darkseid planet?", o:["Apokolips","Krypton","Mars","Earth"], a:0 },
{ q:"Justice League leader?", o:["Batman","Superman","Flash","Aquaman"], a:1 },
{ q:"Wonder Woman origin?", o:["Amazon","Greek","Roman","Egypt"], a:0 },
{ q:"Flash real name?", o:["Barry Allen","Bruce","Clark","Victor"], a:0 },
{ q:"Batman parents killed by?", o:["Joker","Thief","Mob","Unknown"], a:1 },
{ q:"Cyborg half?", o:["Robot","Alien","Magic","Human"], a:0 },
{ q:"Superman planet?", o:["Earth","Mars","Krypton","Venus"], a:2 },
{ q:"Green Arrow weapon?", o:["Gun","Arrow","Sword","Ring"], a:1 },
{ q:"DC speed villain?", o:["Zoom","Thanos","Ultron","Loki"], a:0 },
{ q:"Shazam power word?", o:["Magic","Shazam","Thunder","Power"], a:1 },
{ q:"Batman tech based hero?", o:["Yes","No","Alien","Magic"], a:0 },
{ q:"Justice League HQ?", o:["Batcave","Watchtower","Gotham","Atlantis"], a:1 },

/* ---------- X-MEN (20) ---------- */
{ q:"X-Men leader?", o:["Logan","Cyclops","Magneto","Charles"], a:3 },
{ q:"Professor X power?", o:["Telepathy","Speed","Strength","Time"], a:0 },
{ q:"Magneto controls?", o:["Fire","Metal","Mind","Energy"], a:1 },
{ q:"Wolverine healing?", o:["Slow","Fast","None","Magic"], a:1 },
{ q:"Jean Grey alter ego?", o:["Phoenix","Storm","Rogue","Mystique"], a:0 },
{ q:"Beast color?", o:["Green","Blue","Red","Black"], a:1 },
{ q:"Mystique ability?", o:["Fly","Shape-shift","Teleport","Heal"], a:1 },
{ q:"Storm controls?", o:["Fire","Weather","Earth","Ice"], a:1 },
{ q:"Cyclops power?", o:["Laser eyes","Speed","Telepathy","Strength"], a:0 },
{ q:"X-Men school name?", o:["X Institute","X Mansion","X Academy","X Lab"], a:1 },
{ q:"Logan is?", o:["Human","Mutant","Alien","Robot"], a:1 },
{ q:"Magneto relation?", o:["Enemy","Friend","Father","Teacher"], a:3 },
{ q:"Rogue power?", o:["Steal powers","Speed","Fire","Metal"], a:0 },
{ q:"Deadpool genre?", o:["Serious","Comedy","Horror","Drama"], a:1 },
{ q:"Deadpool healing?", o:["No","Yes","Magic","Tech"], a:1 },
{ q:"X-Men universe?", o:["Marvel","DC","Sony","Fox"], a:0 },
{ q:"Nightcrawler ability?", o:["Fly","Teleport","Invisibility","Fire"], a:1 },
{ q:"Sentinels hunt?", o:["Aliens","Mutants","Humans","Robots"], a:1 },
{ q:"Jean Grey power source?", o:["Stone","Phoenix Force","Ring","Magic"], a:1 },
{ q:"X-Men enemy team?", o:["Avengers","Brotherhood","Justice League","Guardians"], a:1 }
  ],
  
  Knowledge: [
    {q: "What is the capital of Japan?", o: ["Seoul", "Beijing", "Tokyo", "Bangkok"], a: 2},
    {q: "Which planet is known as the Red Planet?", o: ["Venus", "Mars", "Jupiter", "Saturn"], a: 1},
    {q: "Who painted the Mona Lisa?", o: ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], a: 2},
    {q: "What is the largest ocean on Earth?", o: ["Atlantic", "Indian", "Arctic", "Pacific"], a: 3},
    {q: "In which year did World War II end?", o: ["1943", "1944", "1945", "1946"], a: 2},
    {q: "Who discovered penicillin?", o: ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Robert Koch"], a: 1},
    {q: "What is the smallest country in the world?", o: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], a: 1},
    {q: "Which element has the chemical symbol 'Au'?", o: ["Silver", "Gold", "Aluminum", "Argon"], a: 1},
    {q: "Who wrote 'Romeo and Juliet'?", o: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], a: 1},
    {q: "What is the speed of light?", o: ["299,792 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], a: 0},
    {q: "Which is the largest desert in the world?", o: ["Sahara", "Arabian", "Antarctica", "Gobi"], a: 2},
    {q: "Who invented the telephone?", o: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Benjamin Franklin"], a: 1},
    {q: "What is the largest mammal on Earth?", o: ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"], a: 1},
    {q: "Which country is known as the 'Land of the Rising Sun'?", o: ["China", "Japan", "Korea", "Thailand"], a: 1},
    {q: "What is the hardest natural substance on Earth?", o: ["Gold", "Iron", "Diamond", "Platinum"], a: 2}
  ]
};
